#!/bin/bash

echo "=== Tunnel will forward port $1 to http://devtunnel--$2.srg.id.au ==="
cloudflared tunnel create "$2"
cloudflared tunnel --hostname "devtunnel--$2.srg.id.au" --name "$2" --url "localhost:$1"
